<?php
/**
 * @category   Chirag
 * @package    Chirag_Events
 * @author     chirag@czargroup.net
 * @copyright  This file was generated by using Module Creator provided by <developer@czargroup.net>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Chirag\Events\Setup;

use Magento\Framework\Setup\UpgradeSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

/**
 * @codeCoverageIgnore
 */
class UpgradeSchema implements UpgradeSchemaInterface
{
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function upgrade(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
		$installer = $setup;
		$installer->startSetup();

		/**
		 * Creating table chirag_events_table
		 */
		if (version_compare($context->getVersion(), '1.0.2') < 0) {
			$table = $installer->getConnection()->newTable(
				$installer->getTable('chirag_events_table')
			)->addColumn(
				'entity_id',
				\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
				null,
				['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
				'Chirag Events Id'
			)->addColumn(
				'reason',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				255,
				['nullable' => false],
				'Reason'
			)->addColumn(
				'contentdata',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				'64k',
				['nullable' => false],
				'Content'
			)->addColumn(
				'date',
				\Magento\Framework\DB\Ddl\Table::TYPE_DATETIME,
				null,
				['nullable' => false],
				'Choose Date'
			)->addColumn(
				'status',
				\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
				11,
				['nullable' => true,'default' => 1],
				'Status'
			)->addColumn(
				'created_at',
				\Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
				null,
				['nullable' => false],
				'Created At'
			)->addColumn(
				'updated_at',
				\Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
				null,
				['nullable' => false],
				'Updated At'
			)->setComment(
				'Chirag Events Table'
			);
			$installer->getConnection()->createTable($table);
		}
		$installer->endSetup();
	}
}